

CREATE TABLE CUSTOMER (`USERID` INT NOT NULL auto_increment, `FIRSTNAME` TEXT, `LASTNAME` TEXT, `EMAIL` TEXT, PASSWORD TEXT, `GENDER` TEXT,`ADDRESS`TEXT,`PHONENUMBER`TEXT, PRIMARY KEY (`USERID`))
AUTO_INCREMENT=100000;

CREATE TABLE STAFF (`USERID` INT NOT NULL auto_increment, `FIRSTNAME` TEXT, `LASTNAME` TEXT, `EMAIL` TEXT, PASSWORD TEXT, `GENDER` TEXT,`ADDRESS`TEXT,`PHONENUMBER`TEXT, PRIMARY KEY (`USERID`))
AUTO_INCREMENT=100000;

CREATE TABLE SYSTEM_ADMIN (`USERID` INT NOT NULL auto_increment, `FIRSTNAME` TEXT, `LASTNAME` TEXT, `EMAIL` TEXT, PASSWORD TEXT, `GENDER` TEXT,`ADDRESS`TEXT,`PHONENUMBER`TEXT, PRIMARY KEY (`USERID`))
AUTO_INCREMENT=100000;
