# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: npm install --only=dev
- task: Npm@1
  inputs:
     command: 'install'

- task: MysqlDeploymentOnMachineGroup@1
  inputs:
    TaskNameSelector: 'SqlTaskFile'
    SqlFile: 'OnlineFoodOrderingSystem/src/main/java/com/mycompany/onlinefoodorderingsystem/dao/createOrder.sql'
    ServerName: 'localhost'
    DatabaseName: 'ofos'
    SqlUsername: 'root'
    SqlPassword: 'admin'

- task: Maven@3
  inputs:
    mavenPomFile: 'OnlineFoodOrderingSystem/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
